### PR TITLE
Fix deploy crash, Mono crash on AI

### PR DESCRIPTION
**Pull request by dnqbob**
The best way to fix the problem is to persuade upstream change `Deploy()` in `TransformProperties` to `Transform()`. I will also give that a try.

### CODE REVIEW

**Comment by dnqbob** [comment]
I filled https://github.com/OpenRA/OpenRA/pull/21081 on upstream which can also fix deploy crash. If it can be merged then the conflict problem will be solved properly

**Comment by MustaphaTR** [comment]
I was thinking of renaming the GCoD one to (Un)DeployForCondition() but didn't have time on PC for the past few days to do it myself. I'm not sure if renaming a longstanding function for this is the better idea. I wasn't planning to push the code upstream either, it is rather limited working only for GCoD, but not the timed variant.

**Comment by dnqbob** [comment]
I would like both of GCoD and Transform get renamed.

**Comment by dnqbob** [comment]
But yeah let us just rename the GCoD first.

**Comment by dnqbob** [comment]
Changed to `ToggleDeploy/Undeploy` and has no problem for adding timed condition in the future.

**Comment by MustaphaTR** [comment]
> Changed to `ToggleDeploy/Undeploy` and has no problem for adding timed condition in the future.

ToggleDeploy sounds like a function that Deploys a unit if Undeployed and Undeploys if Deployed, while this function Deploys if Undeployed but doesn't do anything if it is already Deployed. I still think DeployForCondition() would be a better name for the current function, tho i guess you could as well merge the functions and keep ToggleDeploy name with the function name fits better to.

**Comment by dnqbob** [comment]
> I still think DeployForCondition() 

In our AS bundle we have  `GrantTimedConditionOnDeploy` and in upstream we have `GrantConditionOnDeployWithCharge`.  ` DeployForCondition()` includes those two in word. We need a name that suggest there is another state besides deploy.

How about `Switch(Un)Deploy` or `SwitchTo(Un)Deploy`?

**Comment by dnqbob** [comment]
Now using `SwitchTo(Un)Deploy`

**Comment by MustaphaTR** [comment]
I was thinking DeployForTimed/ChargedCondition() for the timed versions' name. I don't think the name you used is any less ambigious on which trait it is supposed to work with.

TBH, if we can (i haven't checked if our version has extra function that upstream one doesn't) we should get rid of GTCoD and use the upstream GCoDwC, two do more or less the same thing.

**Comment by dnqbob** [comment]
While `Toggle` has the ambigious meaning that click is on and click again is off, switch is better on describe there is more options. See [here](https://www.merriam-webster.com/dictionary/switch). Use the meaning of "a shift from one to another" is fitting here. 

`DeployForCondition()` also has a flaw on its name: it seems you need to use it as `DeployForCondition(string condition)` like `GrantCondition(string condition)`, but it is not. Although the trait GCoD is related to condition, but its activity exposes outside is nothing related to `Condition`, only deploy and undeploy.

As for GTCoD, I guess we can remove it. In SP there is no problem when I switch to GCoDwC. The difference of those two is the one in AS support animation, the one in upstream support logic similar to ammo. If we have nowhere to use animation function in GTCoD, we can remove it.

**Comment by dnqbob** [comment]
Btw, I think `DeployDischarge()` is better than `DeployForChargedCondition()`, if we are going to make properties for GCoDwC as the reason above.

Additionally, `DeployForChargedCondition()` is not correct: GCoDwC will give a condition when fully charged, and another condition when discharging, I would recommend to use `DeployForDischargingCondition()`, at the very least.

**Comment by dnqbob** [comment]
Note: our GrantConditionOnDeployProperties.cs will be replace later by the same one upstream, we miss some check here (not very important, though)

**Pull request merged**
